### ISSUE TITLE
[Feature Request] Optional deny period for whitelisted invite requests

### ISSUE THREAD

**Issue by Dervali-git** [Psychloor/AdvancedInvites#1]
A great optional feature to have would be to add a notification prompt to whitelisted invite requests that allows you to deny someone joining, or if you don't make a choice in 30 seconds or so, they get the invite. 

Despite wanting some people to be able to join 99% of the time, I could see there being situations where you may want to override that.

**Comment by Psychloor** [comment]
I could just add toggles for both blacklist and whitelist system. bit lazy since last update xD

**Comment by Psychloor** [comment]
changed so you can disable blacklist/whitelist separately if you want to turn off just blocking or just auto-accepting while keeping the opposite
