### ISSUE TITLE
Crashing in Public Worlds - NullReferenceException

### ISSUE THREAD

**Issue by Gamersven** [Psychloor/AdvancedInvites#7]
Hi, 
me and my friends were crashing frequently and i started to investigate the cause.
we found that function AdvancedInvites.Utilities.AllowedToInvite() was crashing us.

After some investigation i found that the OwnerId is null in Public Instances and was causing a System.NullReferenceException.

I fixed it up that i checked if the OwnerId is not null and then proceded.

My Code it kinda trash, so i didint PR it. 

Greetings from Germany and thanks for your work!

![devenv_UoNKkeyp4e](https://user-images.githubusercontent.com/35612832/123874254-265da780-d938-11eb-99a7-e1238394364e.png)

**Comment by Psychloor** [comment]
thank you. gonna add a fix for it
![Screenshot 2021-06-30 155153](https://user-images.githubusercontent.com/4050182/123972445-25ba2500-d9bb-11eb-9101-93e6631b47d4.png)

**Comment by Psychloor** [comment]
uploaded and that line turns into this decompiled
![Screenshot 2021-06-30 161434](https://user-images.githubusercontent.com/4050182/123976333-5780bb00-d9be-11eb-867d-0301423dbbd4.png)

**Comment by Gamersven** [comment]
Nice!
Thank you for the explanation too.

**Comment by Psychloor** [comment]
? is pretty much checking for null. there's also ?? to check if left is null. if it is then right and some others. newer c# like ??= is if this variable is null, then assign this.

name ??= "something";

there's a lot with these questionmarks to do in c# and so far the code you showed isn't really bad. there's also exclamationmark ! in c# whihci  is null supressor. basically ignoring that it might be null and telling it won't be
